import React, { Component } from 'react';
import Colour from './Colour';

  // random colour 
  class Welcome extends Component  {
    state = {
    colour1: Math.floor(Math.random() * 250) + 1,
    colour2: Math.floor(Math.random() * 250) + 1,
    colour3: Math.floor(Math.random() * 250) + 1 
  }

  render() {

    return (
    <div className="App">
      <div className="container">
        <table>
          <tr> 
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
          </tr>
          <tr>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
          </tr>
          <tr>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
          </tr>
          <tr>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
          </tr>
          <tr>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
            <td>
            <Colour
              c1={this.state.colour1}
              c2={this.state.colour2}
              c3={this.state.colour3}
            />
            </td>
          </tr>          
        </table>
      </div>
    </div>

    );
  }
}

export default Welcome;